Add support for pre-commit, checks for mypy,pyright,pylint
Signed-off-by: Nikos Koukis <nickkouk@gmail.com>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,11 +1,20 @@
-#!/bin/sh
-ROOT=$(realpath $(dirname $(readlink -f $0))/..)
-$ROOT/scripts/check_style.py --check-only
-ret=$?
+#!/usr/bin/env bash
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
-if [ $ret = "0" ];
-then
-    echo "$(tput setaf 2)Style checks passed$(tput sgr 0)"
+# start templated
+INSTALL_PYTHON=/home/berger/.cache/pypoetry/virtualenvs/item-synchronizer-e0cfF4-F-py3.8/bin/python
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
+# end templated
+
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
+
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
 else
-    echo "$(tput setaf 1)Style checks failed - ec: $ret\nConsider fixing them for the CI to pass.$(tput sgr 0)"
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
 fi
